### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by natew** [motion/orbit#81]
## Operation: Matt

1. Get a basic splash site so he can ask higher ups
  - [ ] Polish demo for a short looping video for site
  - [ ] Redesign and reword copy on site
  - [ ] Get a test build working to install on his CPU that ideally we can iterate with
  - [ ] Work with him in person to get syncers working + app set up
  - [ ] Auto updating builds
  - [ ] App icon, electron tray icon

## Alpha program
Goal: Get a few people using it and make them love it while iterating using their data.

Specifically: Get Walmart Labs, Target Labs, Formidable, Unity, Toyota TRD Research, Remedy, Pavlov, Front, OpenDoor, a handful more using it. Set up a system that lets us iterate and work with them in a good feedback loop. Also focus on features that make them excited, so we can start building advocates.

1. Communication
- [ ] Slack channel or facebook group thats active and fun

2. First install experience
- [ ] App download page with bundled app
- [ ] Company onboarding -- should we set up prod servers with login/superlogin? or keep it siloed
- [ ] Having it figure out teams/projects with you

## Beta plan
May be worth trying to get a few more big companies on board during the alpha/beta to get their specific feedback. We also should just start curating a best-idea list of what we should work on beyond just bugfixing.

- Integrations
- ...
